LOCAL_PATH := $(call my-dir)
include $(CLEAR_VARS)
LOCAL_MODULE := PdfViewerPlus
LOCAL_MODULE_CLASS := APPS
LOCAL_MULTILIB := both
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_SRC_FILES := com.gsnathan.pdfviewer_28.apk
LOCAL_PRODUCT_MODULE := true
include $(BUILD_PREBUILT)
