LOCAL_PATH := $(call my-dir)
include $(CLEAR_VARS)
LOCAL_MODULE := EtarCalendar
LOCAL_MODULE_CLASS := APPS
LOCAL_MULTILIB := both
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_OVERRIDES_PACKAGES := Etar
LOCAL_SRC_FILES := ws.xsoh.etar.apk
LOCAL_PRODUCT_MODULE := true
include $(BUILD_PREBUILT)
